[#71] 사용자는 가게 상세보기 페이지에서 리뷰를 생성 / 수정 / 삭제할 수 있다.
lucky-treee/ZeroWasteShopMapWebUI pull request #104
Opened 2023-04-08 16:51 UTC by m1nsuppp

# 관련 이슈
#71 사용자는 가게 상세보기 페이지에서 리뷰를 생성 / 수정 / 삭제할 수 있다.

# 내용

다음과 같은 내용을 구현했습니다.

* 리뷰를 생성할 수 있는 `<ReviewRegisterPage />`를 생성했습니다.

# 미리보기

| 내용 | 스크린샷 |
|--|
<img width="357" alt="스크린샷 2023-04-09 오전 1 43 21" src="https://user-images.githubusercontent.com/75208324/230733322-c569434a-8f21-4ab0-a14a-442aa17536fc.png">
|
| -- | <img width="361" alt="스크린샷 2023-04-09 오전 1 46 43" src="https://user-images.githubusercontent.com/75208324/230733302-4b89889e-93b7-4f6f-bb30-b7e5f88cf764.png">|

2023-04-09 09:59 UTC, jeongwoo903 approved these changes
오옹~ 고생하셨습니다~!!

2023-04-10 12:41 UTC, sshrik commented
review 남기실 때 markdown preview 한번 확인 부탁드려용~

아래처럼 되어있어야 table 형식으로 표현됩니다~ 🙂 ( 지금은 제가 수정 해드렸어용~ )

```markdown

| 내용 | 스크린샷 |
| -- | ---- |
|  | <img width="357" alt="스크린샷 2023-04-09 오전 1 43 21" src="https://user-images.githubusercontent.com/75208324/230733322-c569434a-8f21-4ab0-a14a-442aa17536fc.png"> |
|  | <img width="361" alt="스크린샷 2023-04-09 오전 1 46 43" src="https://user-images.githubusercontent.com/75208324/230733302-4b89889e-93b7-4f6f-bb30-b7e5f88cf764.png"> |
```

2023-04-10 13:17 UTC, sshrik requested changes
파일 올리는 부분이 까다로웠는데, 고생하셨습니다~!

2023-04-10 13:17 UTC, sshrik commented on src/assets/components/Cancel.svg
* 아래가 잘린 모양의 x 버튼이라 수정이 필요할 것 같습니다.
* 현재 UI에서 Icon의 형태가 O 로 감싸진 Icon이 아니다보니 그냥 x 모양으로 하는게 좋을 것 같습니다~! ( 말하고보니 네비게이션 쪽도  O로 감싸진 형태가 아닌걸로 바꾸면 좋겠네요! )

2023-04-10 13:17 UTC, sshrik commented on src/components/shop/ReviewRegisterForm.tsx
> +                </button>
<img width="217" alt="image" src="https://user-images.githubusercontent.com/20200204/230904118-8227b389-59cb-4d2d-8f6c-619bc262d15a.png">

아이콘이 삐져 나오게 되어있네요~! 실제 아이콘 크기를 확인하셔서 수정하는 편이 좋을 것 같습니다~

이 부분이 피그마에 빠져있어서 피그마에도 반영 해 두었어요~!

2023-04-10 13:17 UTC, sshrik commented on src/service/shop.ts
> +  images.forEach((image) => formData.append('images', image));
`formData`를 request 형식으로 바꿔주는 것은 hook의 관심사이지 service 코드의 관심사는 아닌 것 같습니다. service 코드에서는 실제 API를 요청하고, 그 요청에 대한 타입 ( FormData를 request로 받아 response로 아무 응답도 내보내지 않는다. ) 만을 관리하도록 하고, 위 `formData` 관련 코드는 API Hook쪽으로 이동하는것이 좋을 것 같아요~

2023-04-10 13:17 UTC, sshrik commented on src/components/shop/ReviewRegisterForm.tsx
> +const MAX_IMAGES = 5;
`MAX_IMAGES` 보다는 `MAX_IMAGE_COUNT` 나 `IMAGE_LIMIT` 같이 해당 상수가 어떤 것을 의미하는지 명확하게 표현하는게 좋을 것 같습니다. `MAX_IMAGES`는 최대 이미지? 하고 한번에 의미가 떠오르지 않는 것 같아요~! 🙂

2023-04-10 13:17 UTC, sshrik commented on src/components/shop/ReviewRegisterForm.tsx
> +                  ref={inputRef}
`ref` 를 사용한 이유가 있을까요? 저장만 하고 사용하진 않는 것 같네요!

2023-04-10 13:17 UTC, sshrik commented on src/components/shop/ReviewRegisterForm.tsx
> +              </label>
`<label />` 컴포넌트 내부에 `<input />` 컴포넌트가 있는 것은 이상한 것 같습니다. `<input />` 컴포넌트의 위치를 밖으로 빼는건 어떨까요?

2023-04-10 13:17 UTC, sshrik commented on src/components/shop/ReviewRegisterForm.tsx
> +              onClick={handleAddImageClick}
암시적으로 `handleAddImageClick` 은 `input`의 file 선택 handler를 호출하도록 되어있네요. 좀 더 명시적으로 `<button />` 컴포넌트의 버튼을 누르면 `inputRef`를 focus 한다던지 해서 파일 선택 창을 띄워준다던지 ( 예시로 생각한거라 이렇게 동작하면 안될수도 있습니다. ) 하게 하는편이 좋을 것 같습니다.

2023-04-10 13:17 UTC, sshrik commented on src/components/shop/ReviewRegisterForm.tsx
> +  };
_최댓값보다 작으면 return, 아니면 addToast 하는 것 보다, 최댓값보다 크면 addToast, 아닌 경우 명시적으로 사진 입력창을 보여준다._ 를 코드로 표현하는 것이 코드를 읽을 때 더 잘 읽히는 것 같아요~!

2023-04-10 13:17 UTC, sshrik commented on src/components/shop/ReviewRegisterForm.tsx
> +    const updatedImages = images.filter((_image) => _image.name !== image.name);
`_` 로 시작하는 변수는 해당 변수를 사용하지 않겠다는 암묵적인 규칙이 있습니다. ( [참고 링크](https://stackoverflow.com/questions/41085189/using-underscore-variable-with-arrow-functions-in-es6-typescript) ) 입력받는 `image` 변수를 `deleteImage` 같이 변경하거나, 

```typescript
const updatedImages = images.filter(({ name } ) => name !== image.name);
```

같이 사용해도 좋을 것 같습니다~ 🙂

2023-04-10 13:17 UTC, sshrik commented on src/components/shop/ReviewRegisterForm.tsx
> +      shopId: parseInt(shopId!, 10),
`non-null assertion` eslint 규칙에 맞게 수정해주세요~

2023-04-10 13:17 UTC, sshrik commented on src/components/shop/ReviewRegisterForm.tsx
> +  };
react-hook-form의 상태에서 images까지 관리되면 좋을 것 같습니다. 기존에 사용하는 `<Image />` 컴포넌트로 사용하면 자동으로 react-hook-form의 상태로 관리되니 그렇게 관리하도록 하는 편이 좋을 것 같아요~! 

추가로 memberId는 어디에 쓰이는 인자일까요~? swagger에 있는 memberId는 access-token이 필요함을 나타내는 의미이지, 이를 실제 body에 넣는다는 의미는 아니라서 제거해도 좋을 것 같습니다~! 🙂 요 부분은 swagger 개선 사항으로 요청해야 겠네용~

2023-04-10 13:19 UTC, sshrik commented
리뷰 고친 부분은 어떻게 고쳤는지 확인을 위해서 아래처럼 커밋 단위로 review에 남겨주심 좋을 것 같아요~

> 말씀해주신 부분 ~ 하게 고쳤습니다~! [68751dbf](https://github.com/lucky-treee/poom-fe/pull/104/commits/68751dbf5e450e02a871b1dcd562f5dc752fdde6) 커밋에서 수정했습니다.

2023-04-10 13:59 UTC, m1nsuppp commented on src/assets/components/Cancel.svg
> * 아래가 잘린 모양의 x 버튼이라 수정이 필요할 것 같습니다.
> * 현재 UI에서 Icon의 형태가 O 로 감싸진 Icon이 아니다보니 그냥 x 모양으로 하는게 좋을 것 같습니다~! ( 말하고보니 네비게이션 쪽도  O로 감싸진 형태가 아닌걸로 바꾸면 좋겠네요! )

네 이 부분은 커밋 body에 작성해두었는데, 어떤 아이콘을 사용하면 좋을지 고민이 돼서 임의로 설정해놓았었습니다.
PR에 적어두었어야 했는데, 깜빡했네요😭

2023-04-11 08:55 UTC, sshrik commented on src/assets/components/Cancel.svg
commit body에 작성해주셨었군요..! 거기까진 보통 보진 않았어서 중요한 내용이면 PR이나 슬랙에도 공유해주시면 좋을 것 같아요~ 🙂

2023-04-11 16:09 UTC, m1nsuppp commented on src/service/shop.ts
> +  images.forEach((image) => formData.append('images', image));
말씀해주신 부분 반영해서 `formData`를 `request`형식으로 변환하는 코드를 `useRegisterReview` hook으로 이동했습니다! [e489cf9807861624c52f2ffb7926005ac8feb43d](https://github.com/lucky-treee/poom-fe/pull/104/commits/e489cf9807861624c52f2ffb7926005ac8feb43d) 커밋에서 수정했습니다.

2023-04-11 16:09 UTC, m1nsuppp commented on src/service/shop.ts
> +  images.forEach((image) => formData.append('images', image));
> `formData`를 request 형식으로 바꿔주는 것은 hook의 관심사이지 service 코드의 관심사는 아닌 것 같습니다. service 코드에서는 실제 API를 요청하고, 그 요청에 대한 타입 ( FormData를 request로 받아 response로 아무 응답도 내보내지 않는다. ) 만을 관리하도록 하고, 위 `formData` 관련 코드는 API Hook쪽으로 이동하는것이 좋을 것 같아요~

말씀해주신 부분 반영해서 formData를 request형식으로 변환하는 코드를 useRegisterReview hook으로 이동했습니다! [e489cf9807861624c52f2ffb7926005ac8feb43d](https://github.com/lucky-treee/poom-fe/pull/104/commits/e489cf9807861624c52f2ffb7926005ac8feb43d) 커밋에서 수정했습니다.

2023-04-11 16:13 UTC, m1nsuppp commented on src/components/shop/ReviewRegisterForm.tsx
> +                  ref={inputRef}
> `ref` 를 사용한 이유가 있을까요? 저장만 하고 사용하진 않는 것 같네요!

처음에는 button에 클릭 이벤트가 발생했을 때, 
```typescript
inputRef.current.focus()
```
위 코드를 실행하려고 작성했었는데, 해당 부분은 [6d1aec04bb77ebb2df5ab06dfa6abc99d21fd4aa](https://github.com/lucky-treee/poom-fe/pull/104/commits/6d1aec04bb77ebb2df5ab06dfa6abc99d21fd4aa) 커밋에서 수정했습니다!

2023-04-11 16:14 UTC, m1nsuppp commented on src/components/shop/ReviewRegisterForm.tsx
> +              </label>
> `<label />` 컴포넌트 내부에 `<input />` 컴포넌트가 있는 것은 이상한 것 같습니다. `<input />` 컴포넌트의 위치를 밖으로 빼는건 어떨까요?

해당 부분 [6d1aec04bb77ebb2df5ab06dfa6abc99d21fd4aa](https://github.com/lucky-treee/poom-fe/pull/104/commits/6d1aec04bb77ebb2df5ab06dfa6abc99d21fd4aa) 커밋에서 피드백 반영하여 `<input />` 컴포넌트의 위치를 `<label />` 밖으로 빼내었습니다!

2023-04-11 16:14 UTC, m1nsuppp commented on src/components/shop/ReviewRegisterForm.tsx
> +  };
> _최댓값보다 작으면 return, 아니면 addToast 하는 것 보다, 최댓값보다 크면 addToast, 아닌 경우 명시적으로 사진 입력창을 보여준다._ 를 코드로 표현하는 것이 코드를 읽을 때 더 잘 읽히는 것 같아요~!

해당 부분은 [6d1aec04bb77ebb2df5ab06dfa6abc99d21fd4aa](https://github.com/lucky-treee/poom-fe/pull/104/commits/6d1aec04bb77ebb2df5ab06dfa6abc99d21fd4aa) 커밋에서 수정했습니다!

2023-04-11 16:15 UTC, m1nsuppp commented on src/components/shop/ReviewRegisterForm.tsx
> +    const updatedImages = images.filter((_image) => _image.name !== image.name);
> `_` 로 시작하는 변수는 해당 변수를 사용하지 않겠다는 암묵적인 규칙이 있습니다. ( [참고 링크](https://stackoverflow.com/questions/41085189/using-underscore-variable-with-arrow-functions-in-es6-typescript) ) 입력받는 `image` 변수를 `deleteImage` 같이 변경하거나,
> 
> ```ts
> const updatedImages = images.filter(({ name } ) => name !== image.name);
> ```
> 
> 같이 사용해도 좋을 것 같습니다~ 🙂

해당 부분은 [6d1aec04bb77ebb2df5ab06dfa6abc99d21fd4aa](https://github.com/lucky-treee/poom-fe/pull/104/commits/6d1aec04bb77ebb2df5ab06dfa6abc99d21fd4aa) 커밋에서 수정했습니다!

`handleImageDelete`의 parameter인 `image`를 `imageToDelete`라는 이름으로 리네이밍 했습니다!

2023-04-11 16:16 UTC, m1nsuppp commented on src/components/shop/ReviewRegisterForm.tsx
> +      shopId: parseInt(shopId!, 10),
> `non-null assertion` eslint 규칙에 맞게 수정해주세요~

해당 부분은 [6d1aec04bb77ebb2df5ab06dfa6abc99d21fd4aa](https://github.com/lucky-treee/poom-fe/pull/104/commits/6d1aec04bb77ebb2df5ab06dfa6abc99d21fd4aa) 커밋에서 수정했습니다!

2023-04-11 16:17 UTC, m1nsuppp commented on src/components/shop/ReviewRegisterForm.tsx
> +  };
> react-hook-form의 상태에서 images까지 관리되면 좋을 것 같습니다. 기존에 사용하는 `<Image />` 컴포넌트로 사용하면 자동으로 react-hook-form의 상태로 관리되니 그렇게 관리하도록 하는 편이 좋을 것 같아요~!
> 
> 추가로 memberId는 어디에 쓰이는 인자일까요~? swagger에 있는 memberId는 access-token이 필요함을 나타내는 의미이지, 이를 실제 body에 넣는다는 의미는 아니라서 제거해도 좋을 것 같습니다~! 🙂 요 부분은 swagger 개선 사항으로 요청해야 겠네용~

넵 맞습니다😭 swagger를 보고 request type을 작성하다가 포함하게 됐습니다..!

해당 부분 반영해서 (6d1aec04bb77ebb2df5ab06dfa6abc99d21fd4aa)[https://github.com/lucky-treee/poom-fe/pull/104/commits/6d1aec04bb77ebb2df5ab06dfa6abc99d21fd4aa]커밋에서 수정했습니다!

2023-04-12 13:34 UTC, sshrik requested changes
사진에 있는 x 모양과 여러 타입 내용 수정 부탁드려용~

2023-04-12 13:34 UTC, sshrik commented on src/components/shop/ReviewRegisterForm.tsx
> +  const imagesRef = useRef<File[]>([]);
`images` 를 state가 아닌 ref로 관리하는 이유가 있을까요?

2023-04-12 13:34 UTC, sshrik commented on src/components/shop/ReviewRegisterForm.tsx
> +              />
컴포넌트에 정의된 `Input` 컴포넌트를 사용해보는건 어떨까요? `register`하는 로직이 내부에 있어서 더 깔끔할 것 같아요.

2023-04-12 13:34 UTC, sshrik commented on src/hooks/api/useRegisterReview.ts
> +      return registerReview(formData);
`RegisterReviewRequest` 타입을 입력받아서 `FormData`를 만들어서 `registerReview` 에 넘겨주는것이 이상한 것 같네요. `Form` 형태의 value를 hook에서 입력받아서 `registerReview` 에서는 `~~Request` 같은 타입을 입력받아 사용하도록 하는것이 좋을 것 같습니다! 🙂

2023-04-12 13:34 UTC, sshrik commented on src/models/review/request.ts
> +} & ReviewRegisterForm;
Request의 타입 형태가 이상하네요. Form과 Request는 서로 연관된 정보지만, 그렇다고 이 경우에 의존 관계를 가지고 있는것이 이상한 것 같습니다.

Form 타입에서는 사용자에게 입력받을 값들만, Request 타입에서는 Service에서 데이터를 보낼 때 필요한 인자들만 사용하도록 하면 좋을 것 같아요~ 🙂

2023-04-12 13:37 UTC, m1nsuppp commented on src/components/shop/ReviewRegisterForm.tsx
> +  const imagesRef = useRef<File[]>([]);
`ref`가 렌더링에 영향을 주지 않아서 선택하게 됐는데, 지금 와서 생각해보니 
함수 내에서 state와 같이 업데이트가 되니 의미가 없어졌네요😅

2023-04-12 13:37 UTC, m1nsuppp commented on src/components/shop/ReviewRegisterForm.tsx
> +  const imagesRef = useRef<File[]>([]);
> `images` 를 state가 아닌 ref로 관리하는 이유가 있을까요?



ref가 렌더링에 영향을 주지 않아서 선택하게 됐는데, 지금 와서 생각해보니
함수 내에서 state와 같이 업데이트가 되니 의미가 없어졌네요😅

2023-04-12 13:40 UTC, m1nsuppp commented on src/components/shop/ReviewRegisterForm.tsx
> +              />
> 컴포넌트에 정의된 `Input` 컴포넌트를 사용해보는건 어떨까요? `register`하는 로직이 내부에 있어서 더 깔끔할 것 같아요.

처음에는 `<Input />` 컴포넌트를 재활용하여 개발하려고 했는데, `multiple` attribute가 적용이 되지 않아서 `<Input />` 컴포넌트의 내용을 변경하려다가 이 방식을 선택하게 됐습니다😭

2023-04-13 14:40 UTC, sshrik commented on src/components/shop/ReviewRegisterForm.tsx
> +  const imagesRef = useRef<File[]>([]);
이부분도 ref 대신 state로 사용하도록 변경해주심 좋을 것 같아요~ 다만 File도 react-hook-form의 상태로 관리할 수 있으니 state로 바꾸는 것 보다도 react-hook-form이 관리할 수 있도록 해주면 좋을 것 같습니다 🙂

2023-04-13 14:45 UTC, sshrik commented on src/components/shop/ReviewRegisterForm.tsx
> +              />
아하 `<Input />` 컴포넌트에 attribute를 하나 추가하는 것 보다 현재 방식이 더 좋다고 느끼신거군요!

코드 변화량은 지금과 같은 방식이 낫겠지만, 이후에 Controlled 입력 방식과 Uncontrolled 입력 방식이 같은 코드 내에서 혼재 되어있다면 새로 추가하는 입력 방식은 어떤걸로 추가해야할지 햇갈릴 수 있을 것 같아요~

혹시 multiple attribute를 추가하기 꺼려지는 이유가 따로 있으셨을까요~?

2023-04-15 06:55 UTC, m1nsuppp commented on src/hooks/api/useRegisterReview.ts
> +      return registerReview(formData);
> `RegisterReviewRequest` 타입을 입력받아서 `FormData`를 만들어서 `registerReview` 에 넘겨주는것이 이상한 것 같네요. `Form` 형태의 value를 hook에서 입력받아서 `registerReview` 에서는 `~~Request` 같은 타입을 입력받아 사용하도록 하는것이 좋을 것 같습니다! 🙂

해당 부분을 [c26b3885504ee88ca2df814b064dcaba7b56c695](https://github.com/lucky-treee/poom-fe/pull/104/commits/c26b3885504ee88ca2df814b064dcaba7b56c695) 커밋에서 수정하였는데, 말씀하신 부분이 잘 이해가 가지 않습니다. 서버에 파일을 요청하기 위해서는 `Form Data` 형식이 요구되는데 결국 서비스에서 `Form Data`로 변환하는 과정이 필요하지 않나싶어서 이렇게 수정하였는데, 어떻게 말씀하신 부분을 반영할지 모르겠네요😭

2023-04-15 06:56 UTC, m1nsuppp commented on src/components/shop/ReviewRegisterForm.tsx
> +              />
> 아하 `<Input />` 컴포넌트에 attribute를 하나 추가하는 것 보다 현재 방식이 더 좋다고 느끼신거군요!
> 
> 코드 변화량은 지금과 같은 방식이 낫겠지만, 이후에 Controlled 입력 방식과 Uncontrolled 입력 방식이 같은 코드 내에서 혼재 되어있다면 새로 추가하는 입력 방식은 어떤걸로 추가해야할지 햇갈릴 수 있을 것 같아요~
> 
> 혹시 multiple attribute를 추가하기 꺼려지는 이유가 따로 있으셨을까요~?

이유는 그저 컴포넌트 수정을 꺼려서였습니다! 그리고 피드백 주신 부분 반영해서 [f2ab75483d3e6238587d451c185a518cefcbcdd6](https://github.com/lucky-treee/poom-fe/pull/104/commits/f2ab75483d3e6238587d451c185a518cefcbcdd6) 커밋에서 수정했습니다!

2023-04-16 13:11 UTC, sshrik commented on src/components/shop/ReviewRegisterForm.tsx
> +      ]);
`prevImages`를 ref나 상태로 저장해야하는 이유가 있나요? react-hook-form의 `watch`나 `getValue`를 사용해서 `setValue` 하는 부분보다 앞에서 값을 가져오면 그 값이 `prevImages` ref / 상태를 대체할 수 있을 뿐더러, UI에는 변화가 없기도 합니다. 🙂

PS. 주석으로 다른 팀원에게 생각한 내용을 공유하기보단 PR의 댓글로 필요한 부분에 추가해두는것이 코드를 읽는 사람과 PR을 읽는 사람을 분리해서 의견을 전달할 수 있어 좋을 것 같습니다. 주석에는 어려운 로직에 대한 설명 ( 이것도 남기지 않는것이 더 좋은 코드일 것 같지만.. ) 외에는 남기지 않는것이 좋을 것 같아요!

2023-04-16 13:14 UTC, m1nsuppp commented on src/components/shop/ReviewRegisterForm.tsx
> +      ]);
> `prevImages`를 ref나 상태로 저장해야하는 이유가 있나요? react-hook-form의 `watch`나 `getValue`를 사용해서 `setValue` 하는 부분보다 앞에서 값을 가져오면 그 값이 `prevImages` ref / 상태를 대체할 수 있을 뿐더러, UI에는 변화가 없기도 합니다. 🙂
> 
> PS. 주석으로 다른 팀원에게 생각한 내용을 공유하기보단 PR의 댓글로 필요한 부분에 추가해두는것이 코드를 읽는 사람과 PR을 읽는 사람을 분리해서 의견을 전달할 수 있어 좋을 것 같습니다. 주석에는 어려운 로직에 대한 설명 ( 이것도 남기지 않는것이 더 좋은 코드일 것 같지만.. ) 외에는 남기지 않는것이 좋을 것 같아요!

`watch`, `getValue`모두 사용해보았지만, 항상 동기화가 됩니다 ㅜㅜ

2023-04-17 01:14 UTC, sshrik commented on src/components/shop/ReviewRegisterForm.tsx
> +const Thumbnial: React.FC<{ image: File }> = ({ image }) => {
* 아무리 간단한 props라도 `ThumbnailProps` 처럼 따로 타입을 줘서 표현해주면 좋을 것 같습니다.
* 컴포넌트명에 오타가 있네요 : `Thumbnial` -> `Thumbnail`

2023-04-17 02:39 UTC, sshrik commented on src/components/shop/ReviewRegisterForm.tsx
> +      ]);
아하 저희가 만든 `Input` 컴포넌트 내부의 `onChange`가 custom하게 설정한 `onChange`보다 더 우선순위가 높아서 그런 것 같네요! 이런 경우는 일반적인 `Input` 보다는 uncontrolled 되는 방식으로 일반 `input` 컴포넌트를 사용하되, 상태는 `react-hook-form`에 맡기도록 구현하면 될 것 같습니다.

다만 현재 구조에 몇가지 문제가 있는데요,

1. `button`으로 감싸져 있어서 event handling이 여러곳에서 일어나고 있어 순서 보장이 어렵다.
2. `button`으로 감싸져 있는 부분은 클릭해도 아무런 변화가 없다.
3. `File`을 여러개 선택한 결과는 `FileList` 타입인데 비해, form 에서는 `File[]` 으로 사용하고 있어 실제 런타임 타입이 깨진다.

다음처럼 변경해서 테스트 해 보았을 때 문제가 없었어요.

먼저 컴포넌트 부분 입니다.

`button` 컴포넌트를 없앴고, File 입력에 대한 이벤트는 `input`의 `onChange`에서만 일어나서 로직이 한곳에서 관리될 수 있게 집중시켰습니다.

```tsx
<section className="w-full flex flex-wrap justify-between gap-y-2">
  <label
    htmlFor="addImage"
    className="flex justify-center items-center w-[168px] h-[168px] rounded-lg bg-black/25 flex-col"
  >
    <CameraIcon />
    <Typography type="caption" className="text-white">
      {t('add-review-image')}
    </Typography>
  </label>
  <input
    id="addImage"
    className="hidden"
    type="file"
    accept="image/*"
    multiple
    {...register('images')}
    onChange={handleImageInputChange}
  />
  {images.map( /* ... 생략 ... */ }
</section>
```

다음은 `onChange`에 들어간 `handleImageInputChange` 부분입니다.

입력으로 들어온 `e.target.files` 는 `FileList` 타입이기 때문에 배열로 변환해서 넣어주는 로직이 추가되었습니다.

```tsx
const images = watch('images');

const handleImageInputChange: ChangeEventHandler<HTMLInputElement> = (e) => {
  const { files } = e.target;

  if (!files) {
    return;
  }

  const totalImages = [...images, ...Array.from(files)];

  if (totalImages.length > MAX_IMAGE_COUNT) {
    addToast({
      type: 'error',
      message: t('add-review-image-error-msg'),
    });

    setValue('images', totalImages.slice(0, MAX_IMAGE_COUNT));
  } else {
    setValue('images', totalImages);
  }
};
```

위 방식대로 하면 될 것 같네요~!

2023-04-17 02:43 UTC, sshrik commented on src/components/shop/ReviewRegisterForm.tsx
> +  const { id: shopId } = useParams<{ id: string }>() ?? '-1';
* `const` 선언은 위와 한칸 띄워서 가독성을 확보하면 좋을 것 같네요~!

* `'-1'` 이 의미없는 값으로 들어가는 것 같습니다. `{ id: '-1' }` 이 의도하신값 같네요! 🙂

2023-04-17 02:47 UTC, sshrik commented on src/components/shop/ReviewRegisterForm.tsx
> +  );
이런 경우는 `react-query`의 `enabled` 속성을 사용해서 `useRegisterReview`의 입력값인 `shopId`를 `undefined` 가능하게 설정하고, `undefined`인 경우 `enabled`를 `false`로 설정하게 하는것이 좋아보여요. API 입장에서는 의미없는 호출이 계속되면 문제가 발생했을 경우 확인하기 어려울 것 같고, API의 목적에 맞게 사용하는것 같지 않아서요~

`shopId`가 없는 경우 `NotFoundPage`로 redirect 시켜주는것이나 찾을 수 없는 id 값에 대한 UI를 보여주는 것이 더 좋겠네요~!

2023-04-17 02:47 UTC, sshrik commented on src/components/shop/ReviewRegisterForm.tsx
> +  const { id: shopId } = useParams<{ id: string }>() ?? '-1';
아래서도 이야기했지만 `shopId`가 없는 경우 `NotFoundPage`로 redirect 시켜주는것이나 찾을 수 없는 id 값에 대한 UI를 보여주는 것이 더 좋겠네요~ 🙂

2023-04-17 14:10 UTC, sshrik approved these changes
고생하셨습니다~🙂

2023-04-17 15:35 UTC, m1nsuppp reviewed
덕분에 또 한 수 배워갑니다 갓갓 현준님👍

2023-04-17 15:35 UTC, m1nsuppp commented on src/hooks/api/useRegisterReview.ts
> +      return registerReview(shopId, { content, images });
이렇게 관리하면 되는 거였군요...!✨

2023-04-17 15:35 UTC, m1nsuppp commented on src/service/shop.ts
> +  return ShopService.post(`/v1/shops/${shopId}/review`, formData, {
이걸 생각 못했네요 ㅜㅜ

2023-04-17 15:35 UTC, merged