[#21] 네비게이션을 통해 페이지를 이동할 수 있다.
lucky-treee/ZeroWasteShopMapWebUI pull request #30
Opened 2023-01-28 19:54 UTC by jeongwoo903

# 관련 이슈

#21 네비게이션을 통해 페이지를 이동할 수 있다.

# 내용

우선 제가 컴포넌트 관리나 파일 관리 같은 것이 미숙해서 조금 난잡할 수 있는데 보시고 조언이나 말씀해주시면 다음주에 후다닥 고쳐두겠습니다!! 

다음과 같은 내용을 구현하였습니다.

* component 파일에 `Navigator.tsx` 컴포넌트를 생성하였습니다. 페이지에 컴포넌트를 삽입하고 `type`을 props로 넘겨 받습니다.
* assets 파일을 생성하였고 svg파일을 tsx로 변환하여 두었습니다. 이 부분은 어떻게 svg를 관리하는 지 몰라서 우선 이러한 방식으로 해두었는데, 문제시 수정 하겠습니다.
* `tailwind.config.cjs`에 spacing을 추가하였습니다. figma에 디자인된 하단 바의 영역을 구현하다보니 52px, 54px이 필요했는데 tailwindcss의 정의되어 있지 않아 우선 따로 정의해 두었습니다.
*  중앙의 샵 추가 버튼은 아직 아무런 기능이 이루어 지지 않습니다.

| 내용 | 스크린샷 |
|-----|---------|
| 페이지 하단의 네이게이션 바를 통해 지도와 프로필 페이지를 이동할 수 있다. | ![화면 기록 2023-01-29 오전 4 50 47 2023-01-29 04_52_53](https://user-images.githubusercontent.com/58330276/215288039-afeb0e4b-39b7-496e-80fe-8959b0327e7a.gif) |

2023-01-29 05:29 UTC, sshrik requested changes
고생하셨습니다~~! 코멘트 남긴것 확인 해 주심 감사하겠습니다~ 🙇

2023-01-29 05:29 UTC, sshrik commented on src/assets/ProfileIcon.tsx
> +const ProfileIcon = (props: any) => (
`ProfileIcon`은 `React` 컴포넌트이므로 `React.FC` 로 타입을 지정해주면 좋을 것 같습니다. `React .FC` 는 함수형 컴포넌트 타입을 정의 해 주므로, `props`의 타입을 자동으로 지정해주니 `any` 타입을 붙이지 않을 수 있을 것 같습니다.

또한 `props`가 `ProfileIcon`에 직접 적용되는 프로퍼티가 아니고 SVG에 적용되는 프로퍼티인 것이 어색하기도 하네요~! 이런 경우는 다음처럼 구현 하는게 더 좋을 것 같습니다~!

```tsx
type ProfileIconType = {
  selected: boolean;
}

const ProfileIcon: React.FC<ProfileIconType> = ({ selected }) => {
  <div className="w-fit m-auto pb-1">
    <svg selected ? 'fill-primary' : 'fill-placeholder'>
    </svg>
  </div>
}
```

2023-01-29 05:29 UTC, sshrik commented on src/components/Navigator.tsx
> +    navigate(`${PathName.MAP_PAGE}`);
의미없는 String Literal 구문인 것 같습니다~ 그냥 `PathName.MAP_PAGE` 같이 작성해도 될 것 같습니다~

`goMap` 같은 함수명 보다는 이 함수가 `MapIconButton`의 클릭 이벤트를 처리 해주는 함수이니 `handleMapIconClick` 같은 함수명이 좀 더 직관적일 것 같아요~

2023-01-29 05:29 UTC, sshrik commented on src/components/Navigator.tsx
> +import Typography from './Typography';
eslint 규칙을 여기서 제한하기 보다는, `import Typography from 'components/Typography` 처럼 작성해주세요~! 

`no-restricted-imports` 규칙을 작성해둔 이유는, 상대 경로를 허용하게 되는 순간 "../../src/assets/SVG/svgIcon.svg" 같이 import 경로를 알아보기 힘들게 작성할 수 있기 때문입니다!

2023-01-29 05:29 UTC, sshrik commented on src/components/Navigator.tsx
> +          <Typography type="caption">지도</Typography>
다국어 지원과 효과적인 문자열 상수 관리를 위해 다음처럼 작성 해 주세요~!

```tsx
const { t } = useTranslation(); // from "react-i18next"

// ...

// Key 이름은 좀 더 직관적인걸로 바꿔도 좋습니다.
<Typography type="caption">{t("map-navigator-menu-text")}</Typography>
```

```tsx
// utils/i18n/locales/ko_KR
{
  "map-navigator-menu-text": "지도"
}
```

2023-01-29 05:29 UTC, sshrik commented on src/components/Navigator.tsx
> +          />
위에서 잠깐 언급했던 것이지만 `ProfileIcon` 컴포넌트가 어떻게 "보일지" 에 관한 내용 ( className ) 은 Icon 컴포넌트 내부에서 결정해주는 것이 더 좋을 것 같습니다~ 지금은 `Navigator` 컴포넌트의 역할이 많아지는 것 같아서요~!

2023-01-29 05:29 UTC, sshrik commented on tailwind.config.cjs
> -      'white-hover': 'rgba(0, 0, 0, 0.05)',
`white-hover`는 사용하는 곳이 없어서 삭제 해주셨군요~ 👍 깜빡했었네요 ㅎㅎ

2023-01-29 05:29 UTC, sshrik commented on tailwind.config.cjs
> +      },
spacing 옆에 주석으로 표시해준 것 좋네요~! 특정 pixel 만큼의 spacing이 필요하다면 `className="w-[52px]"` 처럼 작성해도 되니 참고 해 주세요~!

2023-01-29 05:29 UTC, sshrik commented on src/components/Navigator.tsx
> +// 타입 지정 필요
어떤 타입 지정이 필요한걸까요~?

2023-01-29 05:29 UTC, sshrik commented on src/components/Navigator.tsx
> +  type: 'map' | 'profile';
`ColorProps` 라는 이름 보다는 `Navigator` 컴포넌트의 프로퍼티이므로, `NavigatorProps`정도로 명명하는게 좋아보입니다~

`type` 이라는 이름이`Navigator` 의 타입을 결정하는 것 같아서 어색한 것 같아요~ 타입이라 함은 `Navigator`가 가로 버전인지, 세로 버전인지, 투명한 버전인지 등 버전을 고르는 것 같은 느낌이 들어서요~ `selectedMenu` 나 아니면 `menuType`, 혹은 간단하게 `menu` 같이 좀 더 직관적인 이름을 지어주면 좋을 것 같습니다~

2023-01-29 05:29 UTC, sshrik commented on src/components/Navigator.tsx
> +        className="absolute mb-7 bottom-0 flex justify-center items-center w-13 h-13 rounded-full bg-primary hover:bg-primary-hover drop-shadow"
크 그림자 효과까지 짱이네요 👍 SVG Icon에 그림자 효과를 어떻게 줘야할지 고민했는데, 이렇게 주는 것이 좋겠군요~!

2023-01-29 05:29 UTC, sshrik commented on src/components/Navigator.tsx
> +      <div className="flex justify-center mt-7 btn-container w-full h-13.5 drop-shadow-md-reverse ">
`btn-container`는 어떤 역할을 하는걸까요~?

2023-01-29 15:50 UTC, jeongwoo903 commented on src/assets/AddShopIcon.tsx
> +};
감사합니다..🥲🙇‍♂️ 거의 유료강의 급의 피드백이네요.. 돈 내고 프로젝트 해야할 것 같아요..ㅎㅎㅎ 

이 부분은 comment 확인 후  tsx 컴포넌트를 svg로  바꾸려다 아래 Navigator.tsx의 역할을 줄여야 할 것 같다는 멘트에 우선 tsx로 두어서 작업해두었습니다..😅 svg가 따로 필요한 경우엔 추가해 두겠습니다!

2023-01-29 15:53 UTC, jeongwoo903 commented on src/assets/ProfileIcon.tsx
> +const ProfileIcon = (props: any) => (
확실히 이런식으로 하니 `Navigator.tsx` 에서 보여질 부분이 좀 더 깔끔해지고 코드도 목적이 명확해 지는 것 같아서 좋네요! 적극 반영 하였습니다..ㅎㅎ 👍

2023-01-29 16:06 UTC, jeongwoo903 commented on src/components/Navigator.tsx
> +    navigate(`${PathName.MAP_PAGE}`);
그렇네요..😅 주의하겠습니다!

2023-01-29 16:08 UTC, jeongwoo903 commented on src/components/Navigator.tsx
> +import Typography from './Typography';
음~ 넵! 주의하겠습니다! 👍

2023-01-29 16:09 UTC, jeongwoo903 commented on src/components/Navigator.tsx
> +          <Typography type="caption">지도</Typography>
우선 Key 이름 변경없이 그대로 반영 해두었습니다! 알려주셔서 감사함닷!

2023-01-29 16:11 UTC, jeongwoo903 commented on tailwind.config.cjs
> +      },
오.. 저런 방법이 있는지도 몰랐네요 😅 참고하겠습니다! className="w-[3.25rem]"  이런 식으로도 되는지 궁금하네요 ㅎㅎ

2023-01-29 16:11 UTC, jeongwoo903 commented on src/components/Navigator.tsx
> +// 타입 지정 필요
잔해 같습니다.. 지워두었습니다!

2023-01-29 16:12 UTC, jeongwoo903 commented on src/components/Navigator.tsx
> +  type: 'map' | 'profile';
넵 수정해 두었습니다!

2023-01-29 16:15 UTC, jeongwoo903 commented on src/components/Navigator.tsx
> +      <div className="flex justify-center mt-7 btn-container w-full h-13.5 drop-shadow-md-reverse ">
js를 쓸때 class 명으로 element에 접근하다 보니, div 태그를 쓸 때 이 태그가 뭘 의미하는 지 나타내려고 작성했던 것 같아요 😅. 우선 사용된 class는 아니여서 지워두었습니다!

2023-01-30 03:42 UTC, sshrik requested changes

2023-01-30 03:57 UTC, m1nsuppp reviewed
고생하셨습니다👍

2023-01-30 03:59 UTC, m1nsuppp commented on src/assets/MapIcon.tsx
> +type MapIconType = {
SVG를 리액트 컴포넌트처럼 사용할 수 있습니다!
[ 링크])(https://velog.io/@juno7803/React-React%EC%97%90%EC%84%9C-SVG-%ED%99%9C%EC%9A%A9%ED%95%98%EA%B8%B0)

2023-01-30 04:51 UTC, jeongwoo903 commented on src/index.css
> -  -webkit-tap-highlight-color: transparent;
어제 잘못 push를 해서 파일을 이것저것 수정했는데 그때 누락된것 같습니다..😅 추가해 두었습니다!

2023-01-30 04:54 UTC, jeongwoo903 commented on src/assets/MapIcon.tsx
> +type MapIconType = {
넵! `MapIcon.tsx`와 `Profile.tsx`는 우선 `Navigator.tsx`의 역할을 좀 줄이기 위해 `.tsx`로 선언해 두었습니다! 통일성이나 좀 이상하다고 하면 수정해 두겠습니다!

2023-01-30 11:15 UTC, sshrik approved these changes
고생하셨습니다~ LGTM!

2023-01-30 19:46 UTC, merged