[#14] 네비게이션을 통해 페이지를 이동할 수 있다.
lucky-treee/ZeroWasteShopMapWebUI pull request #51
Opened 2023-02-17 08:41 UTC by jeongwoo903

# 관련 이슈

#14 프로젝트에서 Input, Select, Button을 사용할 수 있다.

# 내용

다음과 같은 내용을 구현했습니다.

* stories 폴더에 다음과 같은 파일들을 생성해 두었습니다. Figma를 보고 참고하여 작성해 두었습니다.
  * `InputBox.stories.tsx`
  * `MainButton.stories.tsx`
  * `OutlineButton.stories.tsx`
* 수정할 사안이나 추가적으로 작성해야할 것이 있으면 알려주시면 해 두겠습니다!

# 미리보기
| 내용 | 스크린샷 |
|-----|---------|
| InputBox | <img width="1680" alt="스크린샷 2023-02-17 오후 5 29 41" src="https://user-images.githubusercontent.com/58330276/219594176-30b6adfd-5228-442f-8e80-97215b238ca1.png"> |   
| MainButton | <img width="1680" alt="스크린샷 2023-02-17 오후 5 35 10" src="https://user-images.githubusercontent.com/58330276/219594422-b1b70b00-5fdf-4616-ab95-7310ed76d778.png"> |
| OutlineButton | <img width="1680" alt="스크린샷 2023-02-17 오후 5 29 27" src="https://user-images.githubusercontent.com/58330276/219594831-c4c07ba8-8280-4107-bdd9-a1ac92ddd752.png"> |

2023-02-17 10:39 UTC, sshrik commented
package에 따로 설치한게 없는데 package-lock.json이 바뀌었네용..? 따로 건든게 있으실까요~?

2023-02-17 10:52 UTC, sshrik requested changes
고생하셨습니다~ 코멘트 참고해서 반영해주세용~ 🙂

2023-02-17 10:52 UTC, sshrik commented on src/stories/InputBox.stories.tsx
> +  </div>
input은 input tag를 활용해서 `src/components` 디렉토리에 컴포넌트로 구현해주시고, StoryBook에는 해당 컴포넌트를 사용하는 방법이나, 해당 컴포넌트가 어떻게 생겼는지 보여주면 좋을 것 같습니다.

2023-02-17 10:52 UTC, sshrik commented on src/stories/MainButton.stories.tsx
> +);
`Hover`는 기존 컴포넌트에 마우스를 올리면 충분히 볼 수 있으니 굳이 Story를 작성하지 않아도 될것 같습니다.

추가로 아시겠지만 혹시나 해서... button 컴포넌트는 `<button />` tag를 활용하는게 좋을 것 같습니다. [관련 링크](https://twitter.com/Steve8708/status/1620448506766045191?s=20&t=EOAcYOg4mVYzzAztNxkvCw)

요기도 컴포넌트로 만들어서 해당 컴포넌트를 사용하는 것을 Story로 남겨주세요~!

2023-02-17 10:52 UTC, sshrik commented on src/stories/OutlineButton.stories.tsx
> +);
버튼은 `Outline` 된 형식과 그렇지 않은 형식 2가지를 하나의 Story에서 버튼의 타입을 다르게 해서 보여주면 좋을 것 같습니다. 위의 버튼과 하나의 버튼으로 `<Button type="outlined">`처럼 쓸 수 있게 만들어주세요~!

2023-02-17 11:03 UTC, sshrik commented
PR 제목이 이상하네용..? `네비게이션을 통해 페이지를 이동할수 있다.` 가 아닌 것 같습니다 🙂

2023-02-18 13:09 UTC, jeongwoo903 commented on src/stories/InputBox.stories.tsx
> +  </div>
넵 알겠습니다! 👍

2023-02-18 13:11 UTC, jeongwoo903 commented on src/stories/MainButton.stories.tsx
> +);
storybook은 그냥 디자인 형식 나타내기 용인줄 알고 `<div>`로 해버렸네요..😅 주의하겠습니다!

2023-02-18 15:39 UTC, m1nsuppp requested changes

2023-02-18 15:39 UTC, m1nsuppp commented on src/stories/InputBox.stories.tsx
> +  </div>
현준님 말씀처럼 div가 아닌 `input`태그로 작성되어야 할 것 같고, 조금 더 편한 사용성을 위해

```js
interface InputProps extends InputHTMLAttributes<HTMLInputElement>  {
  ...
}
와 같이 `prop`을 전달 받을 수 있으면 어떨까 싶습니다!!
```

2023-02-19 15:03 UTC, sshrik requested changes
고생하셨습니다~! `Select` 컴포넌트에 대한 구현은 없는데, 굳이 이번 PR에서 진행하지 않아도 될 것 같긴합니다~ 아직 필요한 곳이 없어서요~

`package-lock.json` 파일이 여전히 git에서 삭제되지 않았네요~!

2023-02-19 15:03 UTC, sshrik commented on src/components/Button.tsx
> +  width: string; // ex) 14px
`width` 프로퍼티는 불필요 해 보입니다. 

가로 길이는 충분히 `className`으로 tailwind css에서 정의한 class로 정의 할 수 있으니 오히려 `className` 을 프로퍼티로 주고, 아래의 `button`에 적용시키는게 더 통일성있는 스타일링이 가능할 것 같습니다. 또한 `className` 은 선택인자로 설정해주면 좋을 것 같아요~ 스타일링이 필요할수도 안할수도 있을 것 같아서요~!

2023-02-19 15:03 UTC, sshrik commented on src/components/Button.tsx
> +  type: 'main' | 'main-s' | 'outlined' | 'outlined-s';
`type`은 `main` / `outlined`로, `size`를 `small` / `default` 로 설정해주면 좋을 것 같습니다. 

또한 버튼의 children이 필수 속성으로 되어있어서 자식이 필요 없는 버튼에도 무조건 자식을 넣어주어야 하게 되어있네요~! 

`?` 을 활용해서 `size`와 `children`을 선택 인자로 변경하면 좋을 것 같습니다. `default` 옵션이 있다면 해당 옵션을 설정하지 않은 경우 기본으로 사용하면 좋을 것 같아요~!

2023-02-19 15:03 UTC, sshrik commented on src/components/Button.tsx
> +        className="flex justify-center items-center bg-white hover:bg-[#F5F5F5] border-[#c5c5c5] hover:border-text border p-2 rounded-md"
색상은 `tailwind.config.cjs` 파일에 정의해서 사용해주세요~! 색상 설정은 한곳에서만 관리되는것이 좋을 것 같아서요~!

2023-02-19 15:03 UTC, sshrik commented on src/components/Button.tsx
> +        style={{ width: `${width}` }}
위에서 `width` props를 제거하면 좋겠다고 말했었으니 요 부분은 사라져야 하겠지만 `{{ width }}` 로만 해도 충분히 설정할 수 있는 부분 같아서 남겨봅니다~! 🙂

2023-02-19 15:03 UTC, sshrik commented on src/components/InputBox.tsx
> +  type: 'default' | 'active' | 'error';
`type`에 default 가 있다면 굳이 `type`을 필수인자로 할 필요는 없을 것 같습니다~! placeholder 또한 원래의 `input`에서 필수인자가 아닌만큼 굳이 필수인자로 줄 필요 없이 `placeholder?: string` 같이 선택 인자로 표현하면 좋을 것 같습니다~!

2023-02-19 15:03 UTC, sshrik commented on src/stories/InputBox.stories.tsx
> +export const Default: ComponentStory<'div'> = () => (
`ComponentStory`의 Generic Type에는 해당 Component의 Type이 들어가야 합니다~ 다른 파일에서 사용하는 것 참고해서 Generic 형식을 변경해주세요~👍

2023-02-19 15:03 UTC, sshrik commented on src/stories/Button.stories.tsx
> +);
가로 길이 설정이 여기서 필요했군요~! 외부에서 해당 컴포넌트의 스타일링이 필요할 때 컴포넌트 라이브러리라면 width, height 같은 스타일링 요소를 노출시킬 수 있지만, 프로젝트 내부에서만 사용할것이라면 `className`으로만 스타일링하는게 더 자연스럽고 일관적인 스타일링이 가능할 것 같아요~!

2023-02-23 14:15 UTC, jeongwoo903 commented on src/components/Button.tsx
> +  width: string; // ex) 14px
넵! tailwindcss 방식의 className을 입력하였을 때 추가적으로 스타일이 적용되게 해두었습니다!

2023-02-23 14:16 UTC, jeongwoo903 commented on src/components/Button.tsx
> +  type: 'main' | 'main-s' | 'outlined' | 'outlined-s';
제가 요부분은 맞게 짠지를 모르겠네요..😅 우선 &&로 type과 size를 묶어서 구별해 두었는데 이상한 부분이 있다면 말씀해주세요~!!

2023-02-23 14:16 UTC, jeongwoo903 commented on src/components/Button.tsx
> +        className="flex justify-center items-center bg-white hover:bg-[#F5F5F5] border-[#c5c5c5] hover:border-text border p-2 rounded-md"
넵 알겠습니다~ ☺️

2023-02-23 14:17 UTC, jeongwoo903 commented on src/components/Button.tsx
> +        style={{ width: `${width}` }}
이거 저도 알고있는 안좋은 습관인데 잘 안 고쳐지네요..ㅎㅎ 😅 주의해야겠네요..🤦🏻‍♂️

2023-02-23 14:18 UTC, jeongwoo903 commented on src/stories/InputBox.stories.tsx
> +export const Default: ComponentStory<'div'> = () => (
오옹.. 이건 몰랐습니다..ㅎ 감사합니다~!!

2023-02-23 14:29 UTC, sshrik approved these changes
고생하셨습니다~! 👍 따로 더 필요한 부분은 프로젝트를 진행하면서 추가하면 좋을 것 같네요~

2023-02-25 06:49 UTC, merged