Feature/issue10
lucky-treee/ZeroWasteShopMapWebUI pull request #55
Opened 2023-02-21 14:25 UTC by m1nsuppp

# 관련 이슈
#10 

# 내용

다음과 같은 내용을 구현했습니다.

* axios instance를 생성했습니다.
* `GET` /shop/get/${maxLat}/${minLat}/${maxLng}/${minLng}에 대한 query를 작성했습니다.

# 미리보기

| 내용 | 스크린샷 |
| -- | ---- |

2023-02-21 14:53 UTC, sshrik requested changes
이전 MR보다 훨씬 코드가 깔끔해졌네요~! 고생하셨습니다~ 🙂👍👍

2023-02-21 14:53 UTC, sshrik commented on package.json
> +    "@tanstack/react-query": "^4.24.9",
react-query가 아닌 tan-stack 을 사용한 이유가 있을까요~?

2023-02-21 14:53 UTC, sshrik commented on src/models/Location.ts
> +  maxLat: number | undefined;
* 전 리뷰에서 궁금했던건데, 해당 필드가 `undefined` 인 이유가 있을까요~? 카카오 API와 호환 때문일까요~?
* 사용하지 않는 Type 같네요~!

2023-02-21 14:53 UTC, sshrik commented on src/models/response.ts
> +export type ShopResponse = {
`ShopResponse` 보다는 `fetchShopList`의 결과이니 `FetchShopListResponse`가 더 명확할 것 같네요~! `ShopResponse`는 `Shop` 정보를 가져오는 것 같은 느낌이 들어서요~

2023-02-21 14:53 UTC, sshrik commented on src/models/Shop.ts
> +};
굳이 Type에 Type을 붙여서 명명하지 않아도 Type임이 명확하니 이런 경우는 그냥 `Shop`만 해줘도 좋을 것 같습니다~!

2023-02-23 14:44 UTC, m1nsuppp commented on src/models/Location.ts
> +  maxLat: number | undefined;
아 요 부분은 `useGeolocated`가 return 하는 `coords`가 `undefined`가 될 수 있기 때문에 잠시 에러만 안맞으려고 설정했었던 거고, 별의미 없습니다!! 그리고 말씀하신대로 사용하지 않는 Type이 될 것 같아서 삭제했습니다~!

2023-02-23 14:46 UTC, closed without merging