[#11] 지도에 가게 정보를 표시할 수 있다.
lucky-treee/ZeroWasteShopMapWebUI pull request #75
Opened 2023-03-08 15:54 UTC by jeongwoo903

# 관련 이슈
#11 지도에 가게 정보를 표시할 수 있다.

# 내용

다음과 같은 내용을 구현했습니다.

* /v1/shop/get 을 통해 전체 가게의 정보를 받은 뒤 마커로 표시함.
* shop 마커를 누르면 토글과 같이 Modal창을 껏다 켰다 할 수 있음.
* Chip의 컴포넌트를 만들고 스토리북에 등록함.

# issue
* 전제 가게의 정보를 받는 부분을 익명함수를 사용하였는데 요청이 계속 re-render 되는듯한 현상이 있음.
* 모달 창 관련하여 name, category, address, review, chip 같은 정보를 받을 수 있는 api가 없어보여서 우선 폼만 만들어 둔 상태임

# 미리보기

| 내용 | 스크린샷 |
| -- | ---- |
| 마커로 가게정보 표시 | <img width="432" alt="스크린샷 2023-03-09 오전 12 44 31" src="https://user-images.githubusercontent.com/58330276/223760930-dd41ba5b-3b8e-4ffb-83c3-6a98ebfafdb3.png"> | 
Modal 창 등록 |  <img width="432" alt="스크린샷 2023-03-09 오전 12 44 49" src="https://user-images.githubusercontent.com/58330276/223761733-e653aab1-3793-4a28-81dd-dace662d53bb.png"> |
Chip 컴포넌트 등록 | <img width="1372" alt="스크린샷 2023-03-09 오전 12 47 11" src="https://user-images.githubusercontent.com/58330276/223762403-065cf494-8dd7-444c-9056-2957f64a9371.png">

2023-03-09 10:16 UTC, sshrik requested changes
매우 고생하셨습니다~ hook을 사용하고, 파일 명만 살짝 변경해주시면 될 것 같아요~

2023-03-09 10:16 UTC, sshrik commented on src/components/Chip.tsx
> +};
오 Typescript 안해보셨는데, `Record` 활용까지~ Good 입니다~

2023-03-09 10:16 UTC, sshrik commented on src/components/ShopModal.tsx
> +            리뷰 2,030개
임시 데이터를 넣어줄 때에는 Modal에 직접 넣지 마시고, `ShopModal`의 props로 전달 해 줄 수 있도록 해 주세요~ 이후에 실제 데이터가 오면 다시 작업해야 해서 작업 량이 늘어나서요~!

2023-03-09 10:16 UTC, sshrik commented on src/components/ShopModal.tsx
> +const ShopModal: React.FC = () => {
좀 더 엄밀히 말하면 아래에서 올라오는 [Drawer](https://www.google.com/search?q=Drawer+UI&tbm=isch&ved=2ahUKEwj3mba_zc79AhWV32EKHbIMAxIQ2-cCegQIABAA#imgrc=hF-8nGFd_FikxM) UI라고 할 수 있겠네요~! `ShopDrawer` 로 표현하는게 좋을 것 같습니다~!

2023-03-09 10:16 UTC, sshrik commented on src/components/map/ShopMarker.tsx
> +// import { ShopService } from 'service';
의미 없는 주석입니다~!

2023-03-09 10:16 UTC, sshrik commented on src/pages/MapPage.tsx
> +  })();
async 호출을 할 때에는 `useFetchShopList` hook으로 이미 생성된 hook을 사용해서 요청 해 주세요~

```typescript
// userLocation에 맞는 정보로 호출하기
const { data } = useFetchShopList(1000, 0, 1000, 0);
```

위 처럼 받아오시면 됩니다~ 위 처럼 받아오면 `shopList` 상태도 삭제되어 더 간단해지겠네요~!

또한 현재 지도 축적 거리에 따라 `- 30` 부분이 변경되어야 할 것 같습니다~!

2023-03-10 13:58 UTC, m1nsuppp commented on src/components/ShopModal.tsx
> +const ShopModal: React.FC = () => {
- 오! 이런 UI 이름이 `Drawer` 였군요,,, 하나 알아갑니다👍

2023-03-12 13:49 UTC, sshrik approved these changes
고생하셨습니다~ 👍 LGTM~!

2023-03-13 01:59 UTC, jeongwoo903 commented on src/components/ShopModal.tsx
> +            리뷰 2,030개
넵! 이 부분은 제가 좀 막연하게 작업 했던것 같네요.. 😅

2023-03-13 02:04 UTC, jeongwoo903 commented on src/pages/MapPage.tsx
> +  })();
제가 promise나 hook에 대해서 지식이 조금 모자랐던것 같네요..🥲 한줄로 요약되니 뭔가 신기하네요 ㅋㅋ 감사합니다~~☺️

2023-03-13 02:04 UTC, merged