[#70] 가게 미리보기를 위로 올려 가게 상세보기를 볼 수 있다.
lucky-treee/ZeroWasteShopMapWebUI pull request #87
Opened 2023-04-01 16:14 UTC by m1nsuppp

# 관련 이슈
#70 가게 미리보기를 위로 올려 가게 상세보기를 볼 수 있다.

# 내용

다음과 같은 내용을 구현했습니다.

* `<Shop />` 컴포넌트를 생성했습니다.
  - @sshrik 님과 @jeongwoo903 님이 잘 구현해놓으신 컴포넌트들과 스타일들을 재사용하여 구현했습니다.
* `<ReviewContent />` 컴포넌트의 내용을 변경했습니다.
 - 마이페이지에서 보여질 `<ReviewContent />`와 다르게 shop에 대한 리뷰는 작성 날짜에 대한 데이터를 렌더링하는 `<LocalDate />`의 위치가 상단에 위치하여, pathname을 기준으로 `<LocaleDate />`를 렌더링하지 않는 방식을 선택했습니다.

---
+ 커밋이 너무 많아서 죄송합니다😭
- 신중하게 커밋해야했는데, 빌드 실패가 너무 많아서 커밋이 많아졌습니다...
- 다음부터는 `lint`와 빌드 체크 후에 신중히 커밋하도록 하겠습니다..!

# 미리보기

| 내용 | 스크린샷 |
| -- | 
<img width="365" alt="스크린샷 2023-04-02 오전 1 10 47" src="https://user-images.githubusercontent.com/75208324/229302213-e0a9ae04-3376-43a4-9a62-3be9d8a7634c.png">
|
| -- | 
<img width="362" alt="스크린샷 2023-04-02 오전 1 11 04" src="https://user-images.githubusercontent.com/75208324/229302225-4024bdcd-0bd2-4be3-9241-b299d209a194.png">
|

2023-04-02 13:32 UTC, sshrik requested changes
고생하셨습니다~ 리뷰 남긴것 반영해주세용~ 👍

2023-04-02 13:32 UTC, sshrik commented on src/service/shop.ts
> +  return ShopService.get<Shop>(`/v1/shops/shop?id=${id}`);
`FetchShopResponse`와 같이 어떤 API 요청에 대한것인지, 응답인지 요청인지 등을 타입으로 나타내면 좋을 것 같네요~!

추가로

```typescript
return ShopService.get<Shop>("/v1/shops/shop", { id });
```
같이 해두면 query paramter로 문자열을 만들어주지 않더라도 작성할 수 있습니다~

2023-04-02 13:32 UTC, sshrik commented on src/service/shop.ts
> +  const { data } = await ShopService.get<ShopReviewListResponse>(
요기도 `FetchShopReviewListResponse`로 타입을 명명하면 좀 더 명확할 것 같습니다~ 🙂

2023-04-02 13:32 UTC, sshrik commented on src/pages/ShopPage.tsx
> +          리뷰 남기기
프로젝트에서 사용하는 문자열 상수는 `useTranslation`을 통해 `i18n` 모듈로 관리할 수 있게 하는게 좋을 것 같습니다. 위의 `리뷰`도 마찬가지로 관리되면 좋겠네요~!

2023-04-02 13:32 UTC, sshrik commented on src/pages/ShopPage.tsx
> +  const { data: reviewList, isLoading: isLoadingReviewList } =
`isLoadingShop` 이나 `isLoadingReviewList` 보다는 `isShopLoading` 과 `isReviewListLoading`과 같은 변수가 좀 더 영어로 번역했을 때 자연스러운 것 같습니다~!

2023-04-02 13:32 UTC, sshrik commented on src/models/auth/Review.ts
> +
위의 `Review` 타입과 Profile 부분이 달라져서 따로 생성한 타입이군요~!


이런 경우 

```typescript
type ReviewWithProfile = { profile : {} } & Review;
``` 

처럼 작성하는것이 더 좋을 것 같습니다. 🙂

2023-04-02 13:32 UTC, sshrik commented on src/hooks/api/useGetShopById.ts
> +    },
`queryKey`는 hook 이름과 동일하게 해주는것이 좋을 것 같습니다. `shop` 이라는 key는 다른 hook에서도 사용할 수 있을 만큼 간단한 이름이라서요~!

2023-04-02 13:32 UTC, sshrik commented on src/components/ReviewContent.tsx
> +      {!pathname.includes('shop') && <LocalDate date={updatedAt} />}
리뷰 관리화면과 가게 상세화면의 날짜 위치가 다르군요!

가게 상세화면의 날짜 위치를 리뷰 관리 화면 처럼 수정하고, 위 로직은 없는것이 더 깔끔할 것 같습니다~!

<img width="357" alt="image" src="https://user-images.githubusercontent.com/20200204/229354957-e35beccb-a414-474c-b0a9-1764be675ceb.png">

2023-04-02 13:32 UTC, sshrik commented on src/components/LocalDate.tsx
> +      className="text-border-gray tracking-[-0.04em]"
👍👍👍

2023-04-02 13:32 UTC, sshrik commented on src/components/shop/Shop.tsx
> +      <div className="w-[95%] text-text mt-2">
width 를 직접 주는 것 보단, 다른 페이지나 컴포넌트처럼 margin을 준 나머지를 전체 너비로 사용하는것이 좋을 것 같습니다. 하위 컴포넌트 내부에서 %단위로 너비를 주게 되면 나중에 각 컴포넌트끼리 크기를 조절할 때 관리하기 힘들더라구요~!

2023-04-02 13:32 UTC, sshrik commented on src/components/shop/Shop.tsx
> +        <Typography type="caption" className="text-disabled">
`text-disabled`라는 색 보다는 `text-gray-500`이 더 좋을 것 같고, 이것보다는 tailwindcss에 하나 더 정의해서  `text-text-gray` 같이 작성하는게 좋을 것 같네요~! 다만 저는 `text-text-gray`는 text가 2번 반복되어 나오고, 파일에 따로 관리해서 얻을 수 있는 이점이 크지 않다고 생각해서 `text-gray-500`으로 작업하고 있긴 합니다.

2023-04-02 13:32 UTC, sshrik commented on src/models/shop/response.ts
> +import { ShopReview } from 'models/auth/Review';
지금 생각해보니 제가 `review`를 `auth`에 정의해뒀군요... 이런 실수를 🙉

2023-04-02 13:32 UTC, sshrik commented on src/models/shop/Shop.ts
> +  shopName: string;
`Shop`이라는 context안에서 `shopName`이 나오는건 불필요한 중복 같습니다. view에서 사용할 model과 실제 API 응답으로 사용할 model을 분리해서 API에서 직접 `Shop` 모델을 사용하는게 아닌, API에서는 `response`에서 정의된 `FetchShopResponse`를 참조하고, hook에서 해당 `Response`를 `Shop` 모델로 변경하는것이 서버의 데이터 변경에서 좀 더 에러가 적고, API와 hook, 컴포넌트간의 결합을 떨어뜨려 유연하게 해 줘서 좋을 것 같습니다.

2023-04-02 14:40 UTC, m1nsuppp commented on src/models/shop/response.ts
> +import { ShopReview } from 'models/auth/Review';
- 리뷰 감사합니다!!👍
일단 해당 부분을 제외하고는 모두 변경사항 반영했습니다~!

2023-04-02 22:58 UTC, jeongwoo903 reviewed
👍 너무 고생하셨습니다~!!

2023-04-03 12:07 UTC, sshrik commented on src/models/shop/response.ts
> +import { ShopReview } from 'models/auth/Review';
요건 따로 이슈따서 변경해두겠습니다~

2023-04-03 12:08 UTC, sshrik approved these changes
고생하셨습니다~ 🙂

2023-04-03 12:30 UTC, merged